### ISSUE TITLE
Apply the new pyramid-app cookiecutter to publisher-account-test-site

### ISSUE THREAD

**Issue by seanh** [hypothesis/publisher-account-test-site#39]

**Comment by robertknight** [comment]
I don't want us to do this. There has been some confusion over the role of this project in the past:

1. Serving as a test site for Hypothesis developers to use when testing third-party authorities
2. Serving as a demonstration site that we can show to external parties, which shows how to use these features

Based on my experience helping users get set up with third-party accounts, we absolutely need (2). For this purpose, we need to keep the setup in this repository as simple as possible, minimizing the amount of boilerplate. This means that I think we _should_ deviate from our regular application project setup.

Also, it needs to not have a hard dependency on `make devdata`.
